read write lock
Karry/libosmscout pull request #2
Opened 2024-01-23 23:28 UTC by janbar

2024-01-23 23:54 UTC, janbar commented
it is a sample. The final implementation should not use std::unique_lock or std::shared_lock. So we have to make own wrappers with functions lock() , unlock() and lock_shared(), unlock_shared().

2024-01-24 09:18 UTC, janbar commented
The last push implements the ReadLock and WriteLock wrapper, with same way of std:shared_lock en std::unique_lock.
Obviously, like the stl wrappers, we cannot exchange those wrappers between thread. The code in libosmscout check that, so no issue.

2024-01-24 12:25 UTC, Karry commented
Well, how own locks are better than STL ones? `std::shared_lock<SharedMutex>` and `std::unique_lock<SharedMutex>`... I do not see any benefit of them. I would prefer standard implementation with less own code to maintain.

In general, I like your implementation without pthread, but it is spin-lock in user-space with all downsides. When writer will be blocked by IO operation for some time and there will be some reader threads waiting for the lock, they will be burning cpu cycles in active waiting loop...

2024-01-24 16:42 UTC, janbar commented
Even, testing I found few cases of deadlock: Some readers hold two or three times the shared lock. When a writer take priority, it is waiting for release of the shared. But those readers are locked trying to lock again.
So it will be nice to find a way avoiding the use of something not implemented by all platforms. I will try to think about this using 2 mutex to make a real LATCH, and I will let you know.

2024-01-24 19:59 UTC, Karry commented
You know, previously DBThread was using QReadWriteLock from Qt. It has writer precedence. But with continuous process to move some basic blocks from cilent-qt library to Qt-less client library, we cannot use this lock in DBThread anymore... I was not aware of the fact that STL implementation behaves differently than Qt one :-/

2024-01-25 10:53 UTC, janbar commented
I guess the issue is the usage of "reentrant mutex", and that cause the deadlock. The std::shared_mutex has writer precedence (have a look in the libstd++ implementation), but you have to care of the readers don't lock more one times. Fixing that is not impossible and even could clarify the code. I could help to fix it, and then we can use the standard std::shared_mutex.

2024-01-26 16:42 UTC, janbar commented
I succeeded to resolve the deadlock. It requires some changes but not too much. I will push my change soon.

2024-01-26 18:37 UTC, janbar commented
The idea is:
- Reader shouldn't lock more than 1 times (non reentrant), obviously a reader cannot lock for shared mode, then lock for exclusive mode.
- A writer lock for exclusive mode, and then it could lock for shared mode too.

2024-01-27 10:16 UTC, janbar commented
I will make an other version supporting reentrant lock for testing. This requires to store an array in Latch containing the reader thread ids that own the shared lock.

2024-01-27 16:51 UTC, janbar commented
Voila !
Now we have a Latch fully re-entrant. And finally no more deadlock, the writers have precedence, and DBLoadJob no longer crash. The blocking uses wait/signal, so no longer a spin lock. I use a spin-lock only for internal access to the s_lockers list.

2024-01-28 17:53 UTC, janbar commented
few bugs fixed, now I am running benchmark on the last push. I will let you know...

2024-01-28 18:12 UTC, janbar commented
few bugs fixed, now I am running benchmark on the last push. I will let you know...

2024-01-29 18:56 UTC, janbar commented
So, I updated the source to remove reentrant reader/writer that required to maintain the shared ids, and now it is comparable i.e same features than pthread. The benchmark is following:

10 readers are executing 2000000 of reads , 2 writers are execution 20000 of increments on the counter.

- pthread:
> time ./build/readwritelock2 
Running (12): counter=0 , readers: ?
Running (12): counter=0 , readers: ?
Running (12): counter=0 , readers: ?
Running (12): counter=0 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (12): counter=1 , readers: ?
Running (11): counter=2 , readers: ?
Running (10): counter=2 , readers: ?
Running (10): counter=222 , readers: ?
Running ( 7): counter=9041 , readers: ?
Running ( 4): counter=28950 , readers: ?
Running ( 3): counter=49666 , readers: ?
Running ( 3): counter=70305 , readers: ?
Running ( 3): counter=400000 , readers: ?
Completed   : counter=400000

**real	0m2,809s**
user	0m17,793s
sys	0m0,432s

- mine:
Running (12): counter=0 , readers: 1
Running (12): counter=13171 , readers: 1
Running (12): counter=32407 , readers: 0
Running (12): counter=52162 , readers: 2
Running (12): counter=76455 , readers: 0
Running (12): counter=97463 , readers: 0
Running (12): counter=117066 , readers: 0
Running (12): counter=137522 , readers: 2
Running (12): counter=161012 , readers: 0
Running (12): counter=184842 , readers: 0
Running (12): counter=206932 , readers: 3
Running (12): counter=231479 , readers: 1
Running (12): counter=248991 , readers: 0
Running (10): counter=266539 , readers: 0
Running ( 8): counter=353887 , readers: 0
Running ( 7): counter=400000 , readers: 0
Completed   : counter=400000

**real	0m1,609s**
user	0m3,051s
sys	0m2,748s

And one remark, pthread seems to be satured on start and writers have not really the priority in this situation.
My latch is never satured and really give the priority to the writers.

2024-01-30 10:05 UTC, Karry requested changes
Hi. I just made fast review, didn't look to correctness yet.

 - Code style is different from the rest of the code, there is used camelCase, not snake_case. It is just style, but it would be great to match with the rest
 - I would suggest you to make this merge request directly to the Tim's upstream and continue with discussion there, not sure if Tim is watching this merge request
 - You wrote that you have some kind of benchmark, it would be great to add it to "Tests" directory and make it part of the test suite, to check locking correctness by Github actions on various platforms.

2024-01-30 10:05 UTC, Karry commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class Latch {
Please add comment with motivation for custom implementation

2024-01-30 10:05 UTC, Karry commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class Latch {
Also, add `OSMSCOUT_API`, build as a shared library fails on Ubuntu:

```
[ 64%] Linking CXX executable ElevationProfileChart
/usr/bin/ld: ../libosmscout-client-qt/libosmscout_client_qtd.so.1.1.1: undefined reference to `osmscout::Latch::unlock_shared()'
/usr/bin/ld: ../libosmscout-client/libosmscout_clientd.so.1.1.1: undefined reference to `osmscout::Latch::unlock()'
/usr/bin/ld: ../libosmscout-client/libosmscout_clientd.so.1.1.1: undefined reference to `osmscout::Latch::lock()'
/usr/bin/ld: ../libosmscout-client-qt/libosmscout_client_qtd.so.1.1.1: undefined reference to `osmscout::Latch::lock_shared()'
collect2: error: ld returned 1 exit status
```

2024-01-30 10:05 UTC, Karry commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class WriteLock
Please add `OSMSCOUT_API`

2024-01-30 10:05 UTC, Karry commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class ReadLock
Please add `OSMSCOUT_API`

2024-01-30 14:23 UTC, janbar commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class ReadLock
I pushed the code relative to the benchmark (non reentrant like pthread) 1 minute ago, so later your review.
I will add more comments about your remarks ...

2024-01-30 14:25 UTC, janbar commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class Latch {
Probably CMakeLists or meson are'nt up to date. Please try with my last push a81b48e.

2024-01-30 14:28 UTC, janbar commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class Latch {
done

2024-01-30 14:29 UTC, janbar commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class WriteLock
done

2024-01-30 14:29 UTC, janbar commented on libosmscout/include/osmscout/async/ReadWriteLock.h
> +class ReadLock
done

2024-01-30 15:02 UTC, janbar commented
I added all comments and I will open a PR for Tim later after adding testing cases.

2024-01-30 18:19 UTC, janbar commented
The new PR for Tim is: https://github.com/Framstag/libosmscout/pull/1555

2024-01-31 18:56 UTC, janbar commented
Hi @Karry, I tested the app in real world in navigation and I noticed the render thread keeps a read lock constantly (in move). It never releses it, i.e the count of reader never get zero, so writer cannot lock to apply style change.
The root cause is a "reentrant reader" that never drop its lock, even if it's just a millisecond.
I resolved that using my first commit of the Latch which store readers ids to avoid reentrant count. So now I try to add again this feature to see what append.

2024-01-31 20:04 UTC, Karry commented
Wow, there is something wrong, because it was working pretty fine with pthread. I will try to reproduce it with your implementation...

2024-01-31 22:55 UTC, janbar commented
@Karry, I found a better way to handle the case, and it works great !  I make the PR ...

Explaination: Instead locking all the time, we pass a ReadLock unlocked to jobs; then on job startup the call DBJob::run() return true or false depending if it succeeded to try_lock(). If false then the job stop immediately returning false.
This strategy works very well, and writers can hold the lock any time.

2024-01-31 23:29 UTC, Karry commented
Take a look to this commit: https://github.com/Framstag/libosmscout/commit/0c9075ddaada4f224d5efb25220cd61fd1448d88

I just added thread_local variable to count how many times one thread is holding shared lock and then debug messages for share lock/unlock method that are printing t_count, s_count, thread name and when t_count==0 it prints how long lock was locked...

I run navigation demo and grep lock log: 
```
./Demos/NavigationSimulation \
  --icons libosmscout/data/icons/svg/standard \
  --translations cmake-build-debug/OSMScout2 \
  from-home-to-work.gpx 2>&1  | grep "s_count" | tee lock.log
```

From the log, it is clear that there are two threads that are using database - map renderer and navigation. But map renderer lock is hold too long sometimes (one minute for example). During debugging, I probably find the cause: `loadJob->deleteLater()` is not called immediately after signal handler, but it is postponed somehow... So, we should close it right away and not wait for destructor. I will send merge request with the fix asap.

2024-01-31 23:34 UTC, janbar commented
Nice !
This proves that pthread_rwlock is too optimistic (bug?) and that it was not blocking the thread writer as it should have been.
QReadWriteMutex could use pthread too underwood.

2024-01-31 23:38 UTC, Karry commented
Please try this change: https://github.com/Framstag/libosmscout/pull/1557

2024-02-01 00:25 UTC, janbar commented
Not fixed. It is better but 10,15 seconds to apply style change.
Applying the commit of the other way I explained above, it get 1 second max to apply style change, or show a new map downloaded. I push the commit to the PR of the Latch to show you.

2024-02-01 00:26 UTC, janbar commented
The commit is "delegates the lock state to the task"

2024-02-26 13:21 UTC, closed without merging